#+TITLE: Contributing to this website.
#+DATE: <2023-01-02 Mon>
#+AUTHOR: Soham S Gumaste
#+EMAIL: sgumas2@uic.edu

* Introduction

This website uses =GNU Emacs= and =org-mode= to manage content.
Org mode files (.org) are converted to HTML files (.html) by Emacs.
It is surprisingly easy to contribute to this website.

* Prerequisites

    1. Get a text editing environment with support for org mode.
       Options include the obvious GNU Emacs but also
       =VS Code= with [[https://marketplace.visualstudio.com/items?itemName=tootone.org-mode][an extension]] or =Vim= by [[https://github.com/jceb/vim-orgmode][committing heresy]]

    2. Be familiar with [[file:content/git.org][Git]].


    
* Contributing

1. Clone the [[https://github.com/lugatuic/new-new-website][GitHub repo]].
2. In the =content/= folder, create a file with a sensible name (in a new branch).
3. Add the following as a header of the file.
   #+BEGIN_SRC org :exports code
     ,#+TITLE: <Page Title>
     ,#+DATE: <YYYY-MM-DD>
     ,#+AUTHOR: Your Full Name
     ,#+EMAIL: netid@uic.edu
   #+END_SRC
4. Write out your contribution article in normal =org-mode= syntax.
5. Test changes locally by running =./build.sh=. The results are in the =public/= folder.
6. Push and create a Pull Request!

   
* Licensing

By contributing, you agree to release your work under the same license as the entire project.
This project is licensed =MIT= and may be changed by the LUG Administration with or wihtout notice.
